name: Research Software Group
description: Fill out this issue form to list your group
labels: ["rse-groups"]
assignees:
  - yiquintero
body:
  - type: markdown
    attributes:
      value: |
        We are looking to publish an overview of groups in the Netherlands with Research Software Engineers (RSEs).
        This can include pure support groups, as well as topic-oriented groups with a strong software component.
        This way, other researchers and RSEs will be able to more easily find you.
        In the title above, please include your institute name (ex: ASTRON support team)
  - type: textarea
    id: group_description
    attributes:
      label: Group description
      description: Describe the lab, research group or research support team you belong to. For labs or research groups, we encourage you to emphasize the research software activities your team is involved in.  
      placeholder: Tell us about your group
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: URL
      description: Do you have a URL for this group?
      placeholder: https://
    validations:
      required: false
  - type: dropdown
    id: group_size
    attributes:
      label: What is your group size in FTE?
      options:
        - 'S: 1-5'
        - 'M: 5-10'
        - 'L: 10-20'
        - 'XL: 20+'
    validations:
      required: true
  - type: dropdown
    id: group_focus
    attributes:
      label: What fraction of the time is spent on research software activities?
      options:
        - '0-20%'
        - '20-40%'
        - '40-60%'
        - '60-80%'
        - '80+%'
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact
      description: Is there an email address or URL to contact this group? Leave blank if same as the URL above.
      placeholder: group.secretary@institute.edu
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can update or remove the information provided by filing an issue or pull request.
        Please email info@nl-rse.org if you'd like to provide this information to us privately or have other questions.